
# Lifted from ropensci-review-tools/srr/R/pkg-skeleton.R

make_pkg_path <- function (base_dir = tempdir (), pkg_name = "demo") {

    d <- file.path (base_dir, pkg_name)
    if (!file.exists (d))
        dir.create (d, recursive = TRUE)

    return (d)
}

get_roxygen_version <- function () {

    ip <- as.data.frame (utils::installed.packages ())
    if (!"roxygen2" %in% ip$Package)
        return (NULL)               # nocov

    return (ip$Version [ip$Package == "roxygen2"])
}

write_desc <- function (d, pkg_name) {

    desc <- c (paste0 ("Package: ", pkg_name),
               "Title: What the Package Does (One Line, Title Case)",
               "Version: 0.0.0.9000",
               "Authors@R: ",
               "  person(given = \"First\",",
               "         family = \"Last\",",
               "         role = c(\"aut\", \"cre\"),",
               "         email = \"first.last@example.com\")",
               "Description: What the package does (one paragraph).",
               "License: GPL-3",
               "Encoding: UTF-8")

    rv <- get_roxygen_version ()
    if (!is.null (rv))
        desc <- c (desc, paste0 ("RoxygenNote: ", rv))

    writeLines (desc, con = file.path (d, "DESCRIPTION"))
}

write_r_fn <- function (d, pkg_name) {

    rfile <- c ("#' test_fn",
                "#'",
                "#' A test funtion",
                "#'",
                "#' @export",
                "test_fn <- function() {",
                "  message(\"This function does nothing\")",
                "}")
    dr <- file.path (d, "R")
    if (!file.exists (dr))
        dir.create (dr)
    writeLines (rfile, con = file.path (dr, "test.R"))

    rfile <- c ("#' @keywords internal",
                "\"_PACKAGE\"",
                "",
                paste0 ("# The following block is used by ",
                        "usethis to automatically manage"),
                "# roxygen namespace tags. Modify with care!",
                "## usethis namespace: start",
                "## usethis namespace: end",
                "NULL")
    writeLines (rfile, con = file.path (dr, paste0 (pkg_name, "-package.R")))
}

write_readme <- function (d, pkg_name) {

    rfile <- c (paste0 ("# ", pkg_name),
                "",
                "This is a skeleton package")

    writeLines (rfile, con = file.path (d, "README.md"))
}

write_namespace <- function (d) {

    nfile <- c ("# Generated by roxygen2: do not edit by hand",
                "",
                "export(test_fn)")
    writeLines (nfile, con = file.path (d, "NAMESPACE"))
}

write_man <- function (d) {

    d <- file.path (d, "man")
    if (!dir.exists (d))
        chk <- dir.create (d, recursive = TRUE)

    x <- c ("% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in R/demo-package.R",
            "\\docType{package}",
            "\\name{demo-package}",
            "\\alias{demo}",
            "\\alias{demo-package}",
            "\\title{demo: What the Package Does (One Line, Title Case)}",
            "\\description{",
            "What the package does (one paragraph).",
            "}",
            "\\author{",
            "\\strong{Maintainer}: First Last \\email{first.last@example.com}",
            "",
            "}",
            "\\keyword{internal}")
    brio::write_lines (x, file.path (d, "demo-package.Rd"))

    x <- c (
            "% Generated by roxygen2: do not edit by hand",
            "% Please edit documentation in R/test.R",
            "\\name{test_fn}",
            "\\alias{test_fn}",
            "\\title{test_fn}",
            "\\usage{",
            "test_fn()",
            "}",
            "\\description{",
            "A test funtion",
            "}")
    brio::write_lines (x, file.path (d, "test_fn.Rd"))
}

make_dummy_pkg <- function (base_dir = tempdir (), pkg_name = "demo") {

    d <- make_pkg_path (base_dir, pkg_name)

    write_desc (d, pkg_name)
    write_r_fn (d, pkg_name)
    write_readme (d, pkg_name)
    write_namespace (d)
    write_man (d)

    return (d)
}
